// -------------------------------------------------------------------------------------------------
//  Copyright (C) 2015-2026 Nautech Systems Pty Ltd. All rights reserved.
//  https://nautechsystems.io
//
//  Licensed under the GNU Lesser General Public License Version 3.0 (the "License");
//  You may not use this file except in compliance with the License.
//  You may obtain a copy of the License at https://www.gnu.org/licenses/lgpl-3.0.en.html
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.
// -------------------------------------------------------------------------------------------------

//! MEXC API credential storage and request signing helpers.
//!
//! # Signing scheme (spot, first-hand from CCXT `mexc.sign()`)
//!
//! For the spot section with `access == 'private'`, CCXT:
//! 1. Appends `timestamp` (ms) and `recvWindow` to the request params (in insertion order),
//! 2. URL-encodes the full param set into `paramsEncoded` (NOT sorted),
//! 3. Computes `signature = hex(HMAC_SHA256(secret, paramsEncoded))`,
//! 4. Appends `&signature=<sig>` to the URL,
//! 5. Sends headers `X-MEXC-APIKEY: <apiKey>` and `source: <broker>`.
//!
//! So the signature is a hex-encoded HMAC-SHA256 over the **exact query string** that is sent
//! (business params, then `timestamp`, then `recvWindow`). We therefore always sign the exact
//! bytes we place on the wire.
//!
//! The **contract/swap** section uses a different scheme (`ApiKey` / `Request-Time` /`Signature`
//! headers, `HMAC_SHA256(secret, apiKey + timestamp + body|sortedQuery)`) and is out of scope for
//! this spot-focused adapter.

use std::fmt::Debug;

use aws_lc_rs::hmac;
use nautilus_core::{env::get_or_env_var_opt, string::secret::REDACTED};
use zeroize::ZeroizeOnDrop;

/// Returns the environment variable names for API credentials.
#[must_use]
pub fn credential_env_vars() -> (&'static str, &'static str) {
    ("MEXC_API_KEY", "MEXC_API_SECRET")
}

/// MEXC API credentials for signing spot requests.
///
/// Uses hex-encoded HMAC-SHA256 for request signing. Secrets are zeroized on drop.
#[derive(Clone, ZeroizeOnDrop)]
pub struct Credential {
    api_key: Box<str>,
    api_secret: Box<[u8]>,
}

impl Debug for Credential {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct(stringify!(Credential))
            .field("api_key", &self.api_key)
            .field("api_secret", &REDACTED)
            .finish()
    }
}

impl Credential {
    /// Creates a new [`Credential`] instance.
    #[must_use]
    pub fn new(api_key: String, api_secret: String) -> Self {
        Self {
            api_key: api_key.into_boxed_str(),
            api_secret: api_secret.into_bytes().into_boxed_slice(),
        }
    }

    /// Resolves credentials from provided values or environment variables.
    #[must_use]
    pub fn resolve(api_key: Option<String>, api_secret: Option<String>) -> Option<Self> {
        let (key_var, secret_var) = credential_env_vars();
        let key = get_or_env_var_opt(api_key, key_var);
        let secret = get_or_env_var_opt(api_secret, secret_var);

        match (key, secret) {
            (Some(k), Some(s)) => Some(Self::new(k, s)),
            _ => None,
        }
    }

    /// Returns the API key.
    #[must_use]
    pub fn api_key(&self) -> &str {
        &self.api_key
    }

    /// Signs a MEXC spot request `query_string` and returns the hex-encoded signature.
    ///
    /// `query_string` must be the exact URL-encoded query placed on the wire (including
    /// `timestamp` and `recvWindow`), matching CCXT's `paramsEncoded`.
    #[must_use]
    pub fn sign(&self, query_string: &str) -> String {
        let key = hmac::Key::new(hmac::HMAC_SHA256, &self.api_secret[..]);
        let tag = hmac::sign(&key, query_string.as_bytes());
        hex::encode(tag.as_ref())
    }

    /// Returns a masked version of the API key for logging purposes.
    #[must_use]
    pub fn api_key_masked(&self) -> String {
        nautilus_core::string::secret::mask_api_key(&self.api_key)
    }
}

#[cfg(test)]
mod tests {
    use rstest::rstest;

    use super::*;

    // Golden vector generated by the CCXT signing logic (Python), see credential.rs docs:
    //   secret = "45d0b3c26f2644f19bfb98b07741b2f5"
    //   query  = "symbol=BTCUSDT&side=BUY&type=LIMIT&quantity=0.001&price=40000\
    //             &timestamp=1700000000000&recvWindow=5000"
    //   sign   = hex(HMAC_SHA256(secret, query))
    const GOLDEN_SECRET: &str = "45d0b3c26f2644f19bfb98b07741b2f5";
    const GOLDEN_QUERY: &str = "symbol=BTCUSDT&side=BUY&type=LIMIT&quantity=0.001&price=40000&timestamp=1700000000000&recvWindow=5000";
    const GOLDEN_SIG: &str = "0dfdfbb6fddbb8d8b016572a4af1f32e89ab0472a34c458d2e6af6f547fce8b3";

    #[rstest]
    fn signing_matches_ccxt_golden_vector() {
        let credential = Credential::new("mx0vglTtestKeyAbc123".to_string(), GOLDEN_SECRET.to_string());
        let signature = credential.sign(GOLDEN_QUERY);
        assert_eq!(signature, GOLDEN_SIG);
    }

    #[rstest]
    fn test_debug_redacts_secret() {
        let credential = Credential::new("mykey".to_string(), GOLDEN_SECRET.to_string());
        let dbg_out = format!("{credential:?}");
        assert!(dbg_out.contains("api_secret: \"<redacted>\""));
        assert!(!dbg_out.contains(GOLDEN_SECRET));
    }

    #[rstest]
    fn test_resolve_partial_returns_none() {
        let (key_var, secret_var) = credential_env_vars();
        if std::env::var(key_var).is_ok() || std::env::var(secret_var).is_ok() {
            return;
        }
        assert!(Credential::resolve(Some("k".to_string()), None).is_none());
    }
}
