// -------------------------------------------------------------------------------------------------
//  Copyright (C) 2015-2026 Nautech Systems Pty Ltd. All rights reserved.
//  https://nautechsystems.io
//
//  Licensed under the GNU Lesser General Public License Version 3.0 (the "License");
//  You may not use this file except in compliance with the License.
//  You may obtain a copy of the License at https://www.gnu.org/licenses/lgpl-3.0.en.html
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.
// -------------------------------------------------------------------------------------------------

//! BingX API credential storage and request signing.
//!
//! Signing is implemented first-hand from the CCXT reference (`ccxt/python/ccxt/bingx.py::sign`,
//! private non-JSON branch used by spot + linear-swap trading):
//! 1. Add `timestamp` (ms) to the business params, then `keysort` (ASCII-ascending key order).
//! 2. `stringToSign = rawencode(params)` — `k=v&k=v` joined in sorted order with RAW
//!    (non-percent-encoded) values; booleans render as `true`/`false`.
//! 3. `signature = hex(HMAC_SHA256(secret, stringToSign))` (lowercase hex).
//! 4. Auth is carried by headers `X-BX-APIKEY` / `X-SOURCE-KEY`; the query sent on the wire is
//!    the percent-ENCODED `urlencode(params)` with `&signature=<sig>` appended.
//!
//! The signed string uses the same key order and (for our simple param sets: symbols, sides,
//! quantities, prices, timestamps) the same bytes as the sent query, since none of those values
//! contain characters that percent-encoding would alter.

use std::{collections::BTreeMap, fmt::Debug};

use aws_lc_rs::hmac;
use nautilus_core::env::get_or_env_var_opt;
use zeroize::ZeroizeOnDrop;

const REDACTED: &str = "<redacted>";

/// Returns the `(key, secret)` environment variable names for BingX credentials.
#[must_use]
pub fn credential_env_vars() -> (&'static str, &'static str) {
    ("BINGX_API_KEY", "BINGX_API_SECRET")
}

/// BingX API credentials for signing requests. The secret is zeroized on drop.
#[derive(Clone, ZeroizeOnDrop)]
pub struct Credential {
    api_key: Box<str>,
    api_secret: Box<[u8]>,
}

impl Debug for Credential {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct(stringify!(Credential))
            .field("api_key", &self.api_key)
            .field("api_secret", &REDACTED)
            .finish()
    }
}

impl Credential {
    /// Creates a new [`Credential`] from raw key/secret strings.
    #[must_use]
    pub fn new(api_key: String, api_secret: String) -> Self {
        Self {
            api_key: api_key.into_boxed_str(),
            api_secret: api_secret.into_bytes().into_boxed_slice(),
        }
    }

    /// Resolves credentials from the provided values or the `BINGX_API_KEY`/`BINGX_API_SECRET`
    /// environment variables. Returns `None` if either is missing.
    #[must_use]
    pub fn resolve(api_key: Option<String>, api_secret: Option<String>) -> Option<Self> {
        let (key_var, secret_var) = credential_env_vars();
        let key = get_or_env_var_opt(api_key, key_var);
        let secret = get_or_env_var_opt(api_secret, secret_var);
        match (key, secret) {
            (Some(k), Some(s)) => Some(Self::new(k, s)),
            _ => None,
        }
    }

    /// Returns the API key.
    #[must_use]
    pub fn api_key(&self) -> &str {
        &self.api_key
    }

    /// Builds the sorted `stringToSign` = `k=v&k=v` joined in ASCII-ascending key order with raw
    /// (non-percent-encoded) values. Mirrors CCXT's `rawencode(keysort(params))`.
    #[must_use]
    pub fn string_to_sign(params: &BTreeMap<String, String>) -> String {
        // BTreeMap iterates keys in ASCII-ascending order (== CCXT keysort).
        params
            .iter()
            .map(|(k, v)| format!("{k}={v}"))
            .collect::<Vec<_>>()
            .join("&")
    }

    /// Computes `signature = hex(HMAC_SHA256(secret, string_to_sign))` (lowercase hex).
    #[must_use]
    pub fn sign(&self, string_to_sign: &str) -> String {
        let key = hmac::Key::new(hmac::HMAC_SHA256, &self.api_secret);
        let tag = hmac::sign(&key, string_to_sign.as_bytes());
        hex::encode(tag.as_ref())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Golden vector cross-generated by executing CCXT's `bingx.sign` algorithm in Python
    /// (`hmac.new(secret, rawencode(keysort(params)), sha256).hexdigest()`), fixed inputs:
    /// `secret=testsecret_short`, business params of a spot LIMIT order + `timestamp`.
    /// See the adapter build notes; the expected `signature` was produced by Python, not by hand.
    #[test]
    fn signing_matches_ccxt_golden_vector() {
        let mut params: BTreeMap<String, String> = BTreeMap::new();
        for (k, v) in [
            ("symbol", "BTC-USDT"),
            ("side", "BUY"),
            ("type", "LIMIT"),
            ("quantity", "0.001"),
            ("price", "50000"),
            ("timestamp", "1700000000000"),
        ] {
            params.insert(k.to_string(), v.to_string());
        }

        let to_sign = Credential::string_to_sign(&params);
        assert_eq!(
            to_sign,
            "price=50000&quantity=0.001&side=BUY&symbol=BTC-USDT&timestamp=1700000000000&type=LIMIT"
        );

        let cred = Credential::new("testkey123".to_string(), "testsecret_short".to_string());
        assert_eq!(
            cred.sign(&to_sign),
            "1d4496992901d0c59df846515d63e3cbd0b900d769371278b55585b38729aefe"
        );
    }
}
