[package]
name = "nautilus-bingx"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
description = "bingx exchange integration adapter for the Nautilus trading engine (WIP)"
categories.workspace = true
keywords.workspace = true
documentation.workspace = true
repository.workspace = true
homepage.workspace = true

[lints]
workspace = true

[lib]
name = "nautilus_bingx"
crate-type = ["rlib"]

[dependencies]
